steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/main-catwalk-374308/nicki-test', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/main-catwalk-374308/nicki-test']